services:
  web:
    build: .
    command: sh -c "pip install psycopg2-binary==2.8.5 && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:17
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"