
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8001:8000
    depends_on:
      - db

    environment:
      # - DJANGO_SETTINGS_MODULE=bookstore.settings
      - DJANGO_SECRET_KEY=django-insecure-t6mpb#uas0vjx^3c^ri#qnw*8x7f@jy&bc^(c!6!ndv(0#&p%_

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: